import { DestructedItem } from "@type/scraped-types"
import { DBItem } from "@type/trinity-types"

export const destructItem = (item: DBItem): DestructedItem => {
  const {
    entry,
    name,
    ItemLevel: itemLevel,
    class: itemClass,
    subclass: itemSubClass,
    Quality: quality,
    InventoryType: inventoryType,
    StatsCount: statsCount,
    stat_type1: statType1,
    stat_value1: statValue1,
    stat_type2: statType2,
    stat_value2: statValue2,
    stat_type3: statType3,
    stat_value3: statValue3,
    stat_type4: statType4,
    stat_value4: statValue4,
    stat_type5: statType5,
    stat_value5: statValue5,
    stat_type6: statType6,
    stat_value6: statValue6,
    stat_type7: statType7,
    stat_value7: statValue7,
    stat_type8: statType8,
    stat_value8: statValue8,
    stat_type9: statType9,
    stat_value9: statValue9,
    stat_type10: statType10,
    stat_value10: statValue10,
    dmg_min1: dmgMin1,
    dmg_max1: dmgMax1,
    dmg_type1: dmgType1,
    dmg_min2: dmgMin2,
    dmg_max2: dmgMax2,
    dmg_type2: dmgType2,
    armor,
    holy_res: holyRes,
    fire_res: fireRes,
    nature_res: natureRes,
    frost_res: frostRes,
    shadow_res: shadowRes,
    arcane_res: arcaneRes,
    Material: material,
    block,
    itemset,
    socketColor_1: socketColor1,
    socketContent_1: socketContent1,
    socketColor_2: socketColor2,
    socketContent_2: socketContent2,
    socketColor_3: socketColor3,
    socketContent_3: socketContent3,
    socketBonus
  } = item

  return {
    entry,
    name,
    itemClass,
    itemSubClass,
    quality,
    inventoryType,
    itemLevel,
    statsCount,
    statType1,
    statValue1,
    statType2,
    statValue2,
    statType3,
    statValue3,
    statType4,
    statValue4,
    statType5,
    statValue5,
    statType6,
    statValue6,
    statType7,
    statValue7,
    statType8,
    statValue8,
    statType9,
    statValue9,
    statType10,
    statValue10,
    dmgMin1,
    dmgMax1,
    dmgType1,
    dmgMin2,
    dmgMax2,
    dmgType2,
    armor,
    holyRes,
    fireRes,
    natureRes,
    frostRes,
    shadowRes,
    arcaneRes,
    material,
    block,
    socketColor1,
    socketContent1,
    socketColor2,
    socketContent2,
    socketColor3,
    socketContent3,
    socketBonus,
    itemset
  }
}
