export interface ItemSet {
  ID: number
  FactionGainID: string
  AlliedChrRacesMask: number
  AtWarChrRacesMask: number
  UnknownCityVal: number
  UnknownHordeCityVal: number
  Unknown_F7: number
  Unknown_F8: number
  Unknown_F9: number
  Unknown_F10: number
  Reputation: number
  Modifier: number
  Modifier2: number
  Modifier3: number
  Unknown_F15: number
  Unknown_F16: number
  Unknown_F17: number
  Unknown_F18: number
  IdParentFaction: number
  Name: number
  Name_KR: number
  Name_FR: number
  Name_GER: number
  Name_CN: number
  Name_TW: number
  Name_ES: number
  Name_RU: number
  field27: number
  field28: number
  field29: number
  field30: number
  field31: number
  field32: number
  field33: number
  field34: number
  NameFlags: number
  Description: number
  Desc_KR: number
  Desc_FR: number
  Desc_GER: number
  Desc_CN: number
  Desc_TW: number
  Desc_ES: number
  Desc_RU: number
  field44: number
  field45: number
  field46: number
  field47: number
  field48: number
  field49: number
  field50: number
  field51: number
  DescFlags: number
}
