import { Enchant } from "./enchants"
import { Gem } from "./gems"

export interface Item {
  item: Optional<DBItem>
  enchant?: Enchant
  gems?: Gem[]
}

export interface DetailedItem {
  item: DBItem
  enchant?: DBItem
  gems?: DBItem[]
}

export interface DBItem {
  entry: number
  class: number
  subclass: number
  SoundOverrideSubclass: number
  name: string
  displayid: number
  Quality: number
  Flags: number
  FlagsExtra: number
  BuyCount: number
  BuyPrice: number
  SellPrice: number
  InventoryType: number
  AllowableClass: number
  AllowableRace: number
  ItemLevel: number
  RequiredLevel: number
  RequiredSkill: number
  RequiredSkillRank: number
  requiredspell: number
  requiredhonorrank: number
  RequiredCityRank: number
  RequiredReputationFaction: number
  RequiredReputationRank: number
  maxcount: number
  stackable: number
  ContainerSlots: number
  StatsCount: number
  stat_type1: number
  stat_value1: number
  stat_type2: number
  stat_value2: number
  stat_type3: number
  stat_value3: number
  stat_type4: number
  stat_value4: number
  stat_type5: number
  stat_value5: number
  stat_type6: number
  stat_value6: number
  stat_type7: number
  stat_value7: number
  stat_type8: number
  stat_value8: number
  stat_type9: number
  stat_value9: number
  stat_type10: number
  stat_value10: number
  ScalingStatDistribution: number
  ScalingStatValue: number
  dmg_min1: number
  dmg_max1: number
  dmg_type1: number
  dmg_min2: number
  dmg_max2: number
  dmg_type2: number
  armor: number
  holy_res: number
  fire_res: number
  nature_res: number
  frost_res: number
  shadow_res: number
  arcane_res: number
  delay: number
  ammo_type: number
  RangedModRange: number
  spellid_1: number
  spelltrigger_1: number
  spellcharges_1: number
  spellppmRate_1: number
  spellcooldown_1: 1000
  spellcategory_1: number
  spellcategorycooldown_1: number
  spellid_2: number
  spelltrigger_2: number
  spellcharges_2: number
  spellppmRate_2: number
  spellcooldown_2: number
  spellcategory_2: number
  spellcategorycooldown_2: number
  spellid_3: number
  spelltrigger_3: number
  spellcharges_3: number
  spellppmRate_3: number
  spellcooldown_3: number
  spellcategory_3: number
  spellcategorycooldown_3: number
  spellid_4: number
  spelltrigger_4: number
  spellcharges_4: number
  spellppmRate_4: number
  spellcooldown_4: number
  spellcategory_4: number
  spellcategorycooldown_4: number
  spellid_5: number
  spelltrigger_5: number
  spellcharges_5: number
  spellppmRate_5: number
  spellcooldown_5: number
  spellcategory_5: number
  spellcategorycooldown_5: number
  bonding: number
  description: string
  PageText: number
  LanguageID: number
  PageMaterial: number
  startquest: number
  lockid: number
  Material: number
  sheath: number
  RandomProperty: number
  RandomSuffix: number
  block: number
  itemset: number
  MaxDurability: number
  area: number
  Map: number
  BagFamily: number
  TotemCategory: number
  socketColor_1: number
  socketContent_1: number
  socketColor_2: number
  socketContent_2: number
  socketColor_3: number
  socketContent_3: number
  socketBonus: number
  GemProperties: number
  RequiredDisenchantSkill: number
  ArmorDamageModifier: number
  duration: number
  ItemLimitCategory: number
  HolidayId: number
  ScriptName: string
  DisenchantID: number
  FoodType: number
  minMoneyLoot: number
  maxMoneyLoot: number
  flagsCustom: number
  VerifiedBuild: 12340
}
